### ISSUE TITLE
Document representation

### ISSUE THREAD

**Issue by rana-alshaikh** [ccmaymay/nhdp#1]
Hi
Does the code generate a vector for each document [1XT] where T is the number of the discovered topics? If not, could you please explain how to change the code to obtain such vectors?

**Comment by ccmaymay** [comment]
Hi,

I'm so sorry, I don't plan to maintain/support this code.  I would recommend looking at [the README](https://github.com/cjmay/nhdp/), which has a link to John Paisley's original code.  I imagine the original code will be much easier to use overall.  In particular, my version of the code assumes your data is stored in a particular format in Redis, and I imagine you're not using Redis for data storage---I don't know anyone who is. :)

Hope this helps,
Chandler
