### ISSUE TITLE
access to MATLAB nHDP code by John Paisley

### ISSUE THREAD

**Issue by yujia0223** [ccmaymay/nhdp#2]
Hi there,

Thanks for your great work. I really want to see the difference between yours and the original one, but the link to original code does not work yet. Could you help me with that?

Best,
Yujia

**Comment by ccmaymay** [comment]
Hi Yujia,

The link to John Paisley's code still works for me, is it possible there is a firewall or something else preventing the download on your end?  You can also see the link listed here: http://www.columbia.edu/~jwp2128/code.html

Alternatively, you can run `git diff 0d196e6` in your clone of the repository or go to https://github.com/ccmaymay/nhdp/compare/0d196e6...main to see the differences.  The first commit in this repository (0d196e6) contains Paisley's code as of 21 December 2015.

Hope this helps!
Chandler

**Comment by yujia0223** [comment]
Hi Chandler,

Thank you a million for your timely response. The link you have sent does really work for me. That reallly helps me a lot.
Thanks again.

Best, 
Yujia
